### ISSUE TITLE
make install rule or documentation of needed files

### ISSUE THREAD

**Issue by Mailaender** [arescentral/antares#166]
It would ease packaging if there was a `make install` rule or some (wiki) documentation of which files have to be placed where.

Bonus points if it would be possible to have game binaries and game files in separated directories that can be defined at build time.

**Comment by Mailaender** [comment]
Bonus points if it would be possible to have game binaries and game files in separated directories that can be defined at build time.

**Comment by sfiera** [comment]
Off the top of my head, a complete Antares installation consists of three parts:
- Binaries. On Linux you'll need `antares` and `antares-install-data` at a minimum. LGPL3.
- Base data. That's the `data/` folder minus docs. Probably belongs in `/usr/share/antares` but I don't recall where it goes now. CC-BY-NC.
- Scenario data. This is proprietary and can't be redistributed in derived form. `antares-install-data` downloads and extracts it to `~/.antares`.

If you're packaging, you might want or need to keep the first two separate because of the differing licenses. I'll leave the bug open pending `make install`.

**Comment by sfiera** [comment]
Matthias, I've just cut the first release candidate for 0.8.2. It moves some things around, for the better I hope. `make install` will put things in the right place, but there's more to worry about if you're packaging:

* `make install-bin` installs the LGPL3 binaries to $DESTDIR$PREFIX/games (changed from bin)
* `make install-data` installs the CC-BY-NC-SA application data to $DESTDIR$PREFIX/share. Most of this goes to /usr/share/games/antares/app (added "games"). There's now also a .desktop file added to /usr/share/applications and icons for it in /usr/share/icons.
* `make install-scenario` installs the factory scenario to $DESTDIR$PREFIX/share/games/antares/scenarios/com.biggerplanet.ares. The result is non-free, so you shouldn't distribute the result of this. Instead, you should run `antares-install-data -s /usr/share/games/antares/downloads -d /usr/share/games/antares/scenarios` on the user's machine when Antares is installed.
* `make install` does the previous three, but you'll probably want to `make install-bin install-data` when packaging to avoid packaging the scenario.

I created four packages for Debian:

* antares-bin, with just the binaries
* antares-data, with the application data in /usr/share/games/antares/app
* antares-scenario, which contains nothing, just runs the installation command above
* antares, with the .desktop and icons, depending on the other three

Mostly, I kept these all separate because with the different licenses that felt "right" to me, but you can keep them together if you find that easier. The packaging scripts are in [arescentral/antares-deb](https://github.com/arescentral/antares-deb) if that's useful to you.

I hope this new setup works for you. I'm happy to wait to finalize 0.8.2 until you've weighed in.
