### ISSUE TITLE
MADH tracks are channel locked, we should play them as such

### ISSUE THREAD

**Issue by mlindner** [arescentral/antares#223]
In pull #220 you change the stereo separation value. This should not be "192" it should be "256". Blending channels was not how the original game functioned.

In the original source code (Music.c):

```
init.numChn		= 4;
init.outPutBits 	= 8;
init.outPutRate		= rate22khz;
init.outPutMode		= StereoOutPut;
init.driverMode		= SoundManagerDriver;
init.antiAliasing	= false;
init.repeatMusic	= true;
init.Interpolation	= false;
init.MicroDelay		= true;
init.MicroDelaySize 	= 40;
init.surround		= true;
init.sysMemory		= false;
```

**Comment by sfiera** [comment]
What’s the argument against considering full separation a bug? If PlayerPro and MADLibrary play the music differently, then I think we should be aiming to reproduce PlayerPro’s output. Per your investigation on #216, that would suggest stereo separation of 128 is correct.

See also: the music files on [Ares Addons](http://www.ambrosiasw.com/games/ares/addons/), supposedly converted to MP3 (and implicitly endorsed) by Nathan. These have some stereo mixing—it sounds like it could be 50%, and probably is, since I’d guess he used PlayerPro to do the conversion.

**Comment by sfiera** [comment]
I adjusted the separation to match PlayerPro. Thanks for the OS9 investigation.

**Comment by mlindner** [comment]
You misunderstood. PlayerPro plays them incorrectly, or rather when it lacks information it assumes some amount of stereo separation. When listened to in the original Ares the channels have full stereo separation.

**Comment by sfiera** [comment]
I understand that Ares and PlayerPro play them differently, and that the new Antares output doesn’t match the old Ares output. I’m choosing to match the PlayerPro output instead of the Ares output. I think PlayerPro’s output is better (and presumably its author agrees), but if there are reasons to match Ares instead (other than for the sake of matching Ares) I’m open to them.
