### ISSUE TITLE
Zoom in/out on macbook keyboard

### ISSUE THREAD

**Issue by johnnyplaydrums** [arescentral/antares#313]
Hey! I'm going through tutorial and it says use "Keypad +" for zooming in. I haven't figured out what keyboard command that is. I've tried `+`, `CMD +`, `CTRL +`, `SHIFT +`, with no luck. I'm on MacOS 10.15.4. Any ideas? Thank you!

**Comment by sfiera** [comment]
Yeah, laptops generally don’t have a numpad (which Ares calls a keypad). You’ll need to rebind the controls to play on a MacBook. I generally bind WASD to the computer controls and Q/E to zooming, myself.

I’ve thought about changing the default controls, since numpads are somewhat rare these days. I haven’t done it because that involves deciding what the new defaults should be.

**Comment by johnnyplaydrums** [comment]
Ah gotcha. Cool thanks I appreciate it!

**Comment by johnnyplaydrums** [comment]
wait sorry can you show me how to map my key bindings like that?

**Comment by sfiera** [comment]
Sure, it’s in Options -> Key Controls.
