### ISSUE TITLE
Mouse selection "goes dead" regularly

### ISSUE THREAD

**Issue by IonicPaul** [arescentral/antares#482]
Possibly a windows-specific bug. Selecting either control or target objects with the mouse is unreliable. Hard to quantify exactly when this happens, but it makes using the mouse unreliable enough that I don't use it unless I have to. Issues seem most common when:

a. The player far from the object he is trying to click on.
b. The display is very zoomed out.
c. The player isn't actively moving the mouse.
d. The player clicks more than twice in one area.

I don't have a Mac or Linux machine on hand to test, but I don't remember clicking being this bad in the original game. I can provide videos, if need be.

**Comment by IonicPaul** [comment]
Actually, with a little more testing, it looks like you simply can't click to select more than twice without having to move your mouse away and back.

**Comment by sfiera** [comment]
Tried the GLFW build on Mac and actually I see the same behavior.

**Comment by sfiera** [comment]
OK, this is at least somewhat intentional.

The game treats double-clicks differently from single-clicks. In the minicomputer, they have different actions. In the main area, both are treated as selection events. But triple-clicks are not; and also, the double-click interval is hard-coded in the GLFW builds to 0.5s (which does appear to be the Windows default).

There’s definitely something weird about treating the double-click as a second selection event and not subsequent clicks, but I don’t recall offhand what the original game’s behavior was.

**Comment by sfiera** [comment]
You can try a test build from https://github.com/arescentral/antares/actions/runs/8417267024?pr=483

**Comment by IonicPaul** [comment]
Works perfectly, can't find any issues!
